import {Application,Assets,Container,Graphics,Sprite,Texture,Text,Rectangle} from 'https://cdn.jsdelivr.net/npm/pixi.js@8.22.0/dist/pixi.min.mjs';
export {Container,Graphics,Sprite,Text,Rectangle};
export const root=document.querySelector('#app'),loading=document.querySelector('#loading'),cityHint=document.querySelector('#cityHint'),restaurantHead=document.querySelector('#restaurantHead'),tools=document.querySelector('#tools'),credit=document.querySelector('#credit'),cityBtn=document.querySelector('#cityBtn'),restaurantBtn=document.querySelector('#restaurantBtn');
export const app=new Application();await app.init({resizeTo:root,background:'#171416',antialias:false,autoDensity:true,resolution:Math.min(devicePixelRatio||1,2),preference:'webgl'});root.prepend(app.canvas);app.stage.eventMode='static';
export const world=new Container();world.sortableChildren=true;app.stage.addChild(world);
export const TW=64,TH=32,CITY_N=26,DIRS=['NE','SE','SW','NW'];
const CITY_BASE='https://raw.githubusercontent.com/matehackers/simate/681a9054255610a74717086db3965befd26b7ada/data/';
const FURN_BASE='https://raw.githubusercontent.com/sfu-gdc/gmtk-2022-game/8f1cbed1cfe77a5ceece818c7d75e1a326953cbe/project/art/3d_object/kenney_furniturePack/Isometric/';
export const state={scene:'city',camera:null,movers:[],selectedTool:'table',rotation:0,deleteMode:false,navigate:null,cityTex:{},furnTex:{},restaurantState:[{type:'table',x:2,y:3,r:0},{type:'chair',x:1,y:3,r:0},{type:'chair',x:4,y:3,r:2},{type:'table',x:4,y:5,r:0},{type:'chair',x:3,y:5,r:0},{type:'chair',x:6,y:5,r:2},{type:'plant',x:0,y:4,r:0}]};
export function iso(x,y,ox=0,oy=0){return{x:ox+(x-y)*TW/2,y:oy+(x+y)*TH/2}}
export function hash(x,y,s=94117){let n=(x*374761393+y*668265263+s*69069)>>>0;n=(n^(n>>13))*1274126177;return((n^(n>>16))>>>0)/4294967295}
export function diamond(cx,cy,fill,stroke=0,w=TW,h=TH){const g=new Graphics(),p=[cx,cy-h/2,cx+w/2,cy,cx,cy+h/2,cx-w/2,cy];g.poly(p).fill(fill);if(stroke)g.poly(p).stroke({color:stroke,width:1});return g}
export function label(s,size=11,color='#fff1cf'){return new Text({text:s,style:{fontFamily:'Georgia, serif',fontSize:size,fill:color,fontWeight:'900',stroke:{color:'#21130d',width:2}}})}
export function clearWorld(){state.movers=[];world.removeChildren().forEach(c=>c.destroy({children:true}))}
function fallback(color=0xb67b58){const c=document.createElement('canvas');c.width=64;c.height=64;const x=c.getContext('2d');x.imageSmoothingEnabled=false;x.fillStyle='#76513a';x.fillRect(15,28,20,28);x.fillStyle=`#${color.toString(16)}`;x.fillRect(35,28,18,28);x.fillStyle='#8b3e31';x.beginPath();x.moveTo(12,28);x.lineTo(34,14);x.lineTo(56,28);x.lineTo(34,40);x.fill();const t=Texture.from(c);t.source.scaleMode='nearest';return t}
async function safe(url,fb){try{const t=await Assets.load(url);t.source.scaleMode='nearest';return t}catch(e){console.warn('asset failed',url);return fb}}
export async function loadAssets(){const fb=fallback();const [small,medium,big]=await Promise.all(['city_small.png','city_medium.png','city_big.png'].map(f=>safe(CITY_BASE+f,fb)));state.cityTex={small,medium,big};const defs={table:'table',chair:'chair',oven:'kitchenStove',bar:'kitchenBar'};for(const[type,name]of Object.entries(defs)){state.furnTex[type]={};for(const d of DIRS)state.furnTex[type][d]=await safe(`${FURN_BASE}${name}_${d}.png`,fb)}state.furnTex.plant={NE:await safe(FURN_BASE+'pottedPlant_NE.png',fb)};state.furnTex.fridge={NE:await safe(FURN_BASE+'kitchenFridge_NE.png',fb)};state.furnTex.sink={NE:await safe(FURN_BASE+'kitchenSink_NE.png',fb)};loading.style.display='none'}
export function makePerson(i){const g=new Graphics(),c=[0xb34536,0x416f98,0x56804b,0xca9a36,0x80567b];g.ellipse(0,1,4,2).fill({color:0,alpha:.22});g.rect(-2,-10,4,7).fill(c[i%c.length]);g.rect(-1,-13,3,3).fill(0xce9870);return g}
export function spriteFor(type,r=0,targetW=58){const set=state.furnTex[type]||{},tex=set[DIRS[((r%4)+4)%4]]||set.NE||fallback();const s=new Sprite(tex);s.anchor.set(.5,.86);s.scale.set(targetW/Math.max(1,tex.width));return s}